collections:
  smells:
    output: true
    permalink: /:path

timezone: Australia/Melbourne

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# SCSS
sass:
  style: compressed

# SEO
title: Code Smells
tagline: Write better smelling code
description: Learn to write less smelly code
author:
  twitter: GavinDouch
twitter:
  username: GavinDouch
  card: summary
logo: /assets/images/logo.png
social:
  name: Gavin Douch
  links:
    - https://twitter.com/GavinDouch
    - https://www.linkedin.com/in/gavin-douch-a77259117/
    - https://github.com/Coedice
    - https://gavindou.ch
locale: en-AU